apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: factorial
  managedFields:
    - manager: kubeEP
      operation: Update
      apiVersion: autoscaling/v1
      fieldsType: "FieldsV1"
      fieldsV1:
        f:spec:
          f:maxReplicas: {}
          f:minReplicas: {}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: factorial
  minReplicas: 5
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50